services:
  kafka-controller-1:
    # image: apache/kafka:3.8.0-rc2
    image: apache/kafka:latest
    container_name: kafka-controller-1
    environment:
      KAFKA_NODE_ID: 1
      CLUSTER_ID: teste121221
      KAFKA_PROCESS_ROLES: controller
      KAFKA_LISTENERS: CONTROLLER://kafka-controller-1:9093
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT
      # KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-controller-1:9093,2@kafka-controller-2:9094,3@kafka-controller-3:9095
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-controller-1:9093
      LOG4J_LOGGER_KAFKA: 'warn'
      LOG4J_LOGGER_ORG_APACHE_KAFKA: 'warn'
      
  # kafka-controller-2:
  #   image: apache/kafka:latest
  #   container_name: kafka-controller-2
  #   environment:
  #     KAFKA_NODE_ID: 2
  #     CLUSTER_ID: teste121221
  #     KAFKA_PROCESS_ROLES: controller
  #     KAFKA_LISTENERS: CONTROLLER://kafka-controller-2:9094
  #     KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
  #     KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT
  #     KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-controller-1:9093,2@kafka-controller-2:9094,3@kafka-controller-3:9095

  # kafka-controller-3:
  #   image: apache/kafka:latest
  #   container_name: kafka-controller-3
  #   environment:
  #     KAFKA_NODE_ID: 3
  #     CLUSTER_ID: teste121221
  #     KAFKA_PROCESS_ROLES: controller
  #     KAFKA_LISTENERS: CONTROLLER://kafka-controller-3:9095
  #     KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
  #     KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT
  #     KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-controller-1:9093,2@kafka-controller-2:9094,3@kafka-controller-3:9095
  
  kafka-broker-1:
    # image: apache/kafka:3.8.0-rc2
    image: apache/kafka:latest
    container_name: kafka-broker-1
    ports:
      - 29092:9090
    environment:
      KAFKA_NODE_ID: 4
      CLUSTER_ID: teste121221
      KAFKA_PROCESS_ROLES: broker
      KAFKA_LISTENERS: 'BROKER://:19090,DOCKER://0.0.0.0:9090'
      KAFKA_ADVERTISED_LISTENERS: 'BROKER://kafka-broker-1:19090,DOCKER://192.168.4.163:29092'
      # KAFKA_ADVERTISED_LISTENERS: 'BROKER://kafka-broker-1:19090,DOCKER://192.168.3.55:29092'
      KAFKA_INTER_BROKER_LISTENER_NAME: BROKER
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,BROKER:PLAINTEXT,DOCKER:PLAINTEXT
      # KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-controller-1:9093,2@kafka-controller-2:9094,3@kafka-controller-3:9095
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-controller-1:9093
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 5
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR : 1
      # KAFKA_REPLICA_SOCKET_RECEIVE_BUFFER_BYTES: 0
      LOG4J_LOGGER_KAFKA: 'warn'
      LOG4J_LOGGER_ORG_APACHE_KAFKA: 'warn'
    depends_on:
      - kafka-controller-1
      # - kafka-controller-2
      # - kafka-controller-3

  # kafka-broker-2:
  #   image: apache/kafka:latest
  #   container_name: kafka-broker-2
  #   ports:
  #     - 29093:9091
  #   environment:
  #     KAFKA_NODE_ID: 5
  #     CLUSTER_ID: teste121221
  #     KAFKA_PROCESS_ROLES: broker
  #     KAFKA_LISTENERS: 'BROKER://:19091,DOCKER://0.0.0.0:9091'
  #     KAFKA_ADVERTISED_LISTENERS: 'BROKER://kafka-broker-2:19091,DOCKER://192.168.18.10:29093'
  #     KAFKA_INTER_BROKER_LISTENER_NAME: BROKER
  #     KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
  #     KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,BROKER:PLAINTEXT,DOCKER:PLAINTEXT
  #     KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-controller-1:9093,2@kafka-controller-2:9094,3@kafka-controller-3:9095
  #     KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 5
  #   depends_on:
  #     - kafka-controller-1
  #     - kafka-controller-2
  #     - kafka-controller-3

  # kafka-broker-3:
  #   image: apache/kafka:latest
  #   container_name: kafka-broker-3
  #   ports:
  #     - 29094:9092
  #   environment:
  #     KAFKA_NODE_ID: 6
  #     CLUSTER_ID: teste121221
  #     KAFKA_PROCESS_ROLES: broker
  #     KAFKA_LISTENERS: 'BROKER://:19092,DOCKER://0.0.0.0:9092'
  #     KAFKA_ADVERTISED_LISTENERS: 'BROKER://kafka-broker-3:19092,DOCKER://192.168.18.10:29094'
  #     KAFKA_INTER_BROKER_LISTENER_NAME: BROKER
  #     KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
  #     KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,BROKER:PLAINTEXT,DOCKER:PLAINTEXT
  #     KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-controller-1:9093,2@kafka-controller-2:9094,3@kafka-controller-3:9095
  #     KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 5
  #   depends_on:
  #     - kafka-controller-1
  #     - kafka-controller-2
  #     - kafka-controller-3
    
  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    volumes:
      - ./dynamic_config.yaml:/etc/kafkaui/dynamic_config.yaml
    ports:
      - 9270:8080
    depends_on:
      - kafka-broker-1
      # - kafka-broker-2
      # - kafka-broker-3
      - kafka-controller-1
      # - kafka-controller-2
      # - kafka-controller-3
    environment:
      # DYNAMIC_CONFIG_ENABLED: true
      KAFKA_CLUSTERS_0_NAME: teste
      # KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka-broker-1:9090,kafka-broker-2:9091,kafka-broker-3:9092
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka-broker-1:9090
      # KAFKA_CLUSTERS_0_METRICS_PORT: 19092
      # SERVER_SERVLET_CONTEXT_PATH: /kafkaui
      # AUTH_TYPE: "LOGIN_FORM"
      # SPRING_SECURITY_USER_NAME: admin
      # SPRING_SECURITY_USER_PASSWORD: pass

# networks:
#   kafka_default:
#       name: kafka_default
#       external: true
 
  wireshark:
    image: lscr.io/linuxserver/wireshark:latest
    container_name: wireshark
    cap_add:
      - NET_ADMIN
    security_opt:
      - seccomp:unconfined #optional
    # network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /path/to/wireshark/config:/config
    ports:
      - 3000:3000 #optional
      - 3001:3001 #optional
    restart: unless-stopped