name: dart_kafka
description: An Open Source project that implements the Apache Kafka's Protocol to be used in Flutter apps and take the integration to the next level!
version: 1.0.2
repository: https://github.com/EduHC/dart-kafka

environment:
  sdk: ^3.6.0

dependencies:
  collection: ^1.19.1
  
dev_dependencies:
  dart_code_metrics: ^5.7.6
  lints: ^4.0.0
  test: ^1.24.0
